#!/usr/bin/env python3
"""Parse the IFA captures in data/ifa/ into data/raw/parsed/seasons_ifa.csv.

Output columns: season,season_start,league,division,position,club

This source has no fetch script, and that is deliberate rather than an
oversight.  football.org.il sits behind a Cloudflare challenge that a scripted
request cannot pass - curl gets the "Attention Required" interstitial where it
expects the page - so the tables were read out of a real browser session and
committed as JSON.  That is why data/ifa/ lives outside the gitignored
data/raw/: nothing here can be regenerated by running a script, so losing it
would mean losing the data.  docs/SOURCES.md records how to capture more.

The IFA is the federation's own record and the only source for tiers three and
below after 2020/21, where English Wikipedia's coverage stops.  It is also the
only source that resolves the seasons Wikipedia skipped outright: 2016/17 and
2018/19 Liga Bet have no article in either language.

What a capture holds is one league-season's final table, already ordered.  The
positions are therefore taken from the list order and checked against the
position the site printed, the same rule parse.py applies to RSSSF.

A capture marked `"abandoned": true` is different: it is where a division
stopped, not where it finished.  Those contribute no positions at all - a
partial table is not a final position, the same rule that drops the 1947/48 rows
in build.py - but they are still worth committing, because they are the only
record that a club was *playing* that season.  Without them a club whose last
final position is 2024/25 renders as though it had ceased to exist, which for
Shimshon Tel Aviv, Maccabi Kiryat Gat and four others would be plainly wrong.
render.py reads them back for exactly that.
"""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CAPTURES = ROOT / "data" / "ifa"
ALIASES = ROOT / "data" / "aliases_ifa.json"
OUT = ROOT / "data" / "raw" / "parsed" / "seasons_ifa.csv"


def main() -> None:
    aliases = json.loads(ALIASES.read_text())["aliases"]
    rows, unmapped, notes = [], set(), []
    abandoned_clubs: set[tuple[str, str]] = set()

    for path in sorted(CAPTURES.glob("*.json")):
        cap = json.loads(path.read_text())
        standings = cap["standings"]

        if cap.get("abandoned"):
            # No positions from a table that never reached the end. The clubs in
            # it are read directly from data/ifa/ by render.py; an unmapped name
            # here is reported rather than fatal, because these divisions are
            # full of clubs this project has no reason to name.
            named = [s["club"] for s in standings if s["club"] in aliases]
            notes.append(
                f"  {path.name}: abandoned after ~{standings[0].get('games_played')} "
                f"of {cap.get('full_schedule')} games - no positions taken, "
                f"{len(named)} of {len(standings)} clubs recognised")
            abandoned_clubs.update((cap["season"], aliases[n]) for n in named)
            continue

        # The captures are ordered tables, so position is row order. The site's
        # own numbering is checked against it rather than trusted: RSSSF has a
        # season where the printed numbers skip one and repeat another, and
        # there is no reason to assume the IFA never does.
        printed = [s["position"] for s in standings]
        if printed != list(range(1, len(standings) + 1)):
            print(f"  {path.name}: printed positions are not a contiguous 1..N "
                  f"({printed}); using row order")

        for i, entry in enumerate(standings, start=1):
            name = entry["club"]
            club = aliases.get(name)
            if club is None:
                unmapped.add(name)
                continue
            rows.append({
                "season": cap["season"],
                "season_start": cap["season_start"],
                "league": cap["league"],
                "division": cap["division"],
                "position": i,
                "club": club,
            })

        if cap.get("note"):
            notes.append(f"  {path.name}: {cap['note']}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["season", "season_start", "league",
                                           "division", "position", "club"])
        w.writeheader()
        w.writerows(rows)

    seasons = {(r["season"], r["league"], r["division"]) for r in rows}
    print(f"{len(rows)} rows from {len(seasons)} league-seasons -> {OUT}")
    if abandoned_clubs:
        by_season: dict[str, int] = {}
        for season, _club in abandoned_clubs:
            by_season[season] = by_season.get(season, 0) + 1
        print("clubs recorded as playing in an abandoned season (no positions): "
              + ", ".join(f"{s}: {n}" for s, n in sorted(by_season.items())))
    if notes:
        print("notes on the captures:")
        print("\n".join(notes))
    if unmapped:
        # Unlike the Wikipedia parsers this is a hard stop. A capture is a whole
        # final table; dropping a club from it would renumber everyone below
        # them, turning a missing alias into wrong positions rather than a
        # missing row.
        raise SystemExit(
            f"{len(unmapped)} club names missing from data/aliases_ifa.json:\n  "
            + "\n  ".join(sorted(unmapped)))


if __name__ == "__main__":
    main()
