#!/usr/bin/env python3
"""Parse the IFA captures in data/ifa/ into data/raw/parsed/seasons_ifa.csv.

Output columns: season,season_start,league,division,position,club

This source has no fetch script, and that is deliberate rather than an
oversight.  football.org.il sits behind a Cloudflare challenge that a scripted
request cannot pass - curl gets the "Attention Required" interstitial where it
expects the page - so the tables were read out of a real browser session and
committed as JSON.  That is why data/ifa/ lives outside the gitignored
data/raw/: nothing here can be regenerated by running a script, so losing it
would mean losing the data.  docs/SOURCES.md records how to capture more.

The IFA is the federation's own record and the only source for tiers three and
below after 2020/21, where English Wikipedia's coverage stops.  It is also the
only source that resolves the seasons Wikipedia skipped outright: 2016/17 and
2018/19 Liga Bet have no article in either language.

What a capture holds is one league-season's final table, already ordered.  The
positions are therefore taken from the list order and checked against the
position the site printed, the same rule parse.py applies to RSSSF.
"""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CAPTURES = ROOT / "data" / "ifa"
ALIASES = ROOT / "data" / "aliases_ifa.json"
OUT = ROOT / "data" / "raw" / "parsed" / "seasons_ifa.csv"


def main() -> None:
    aliases = json.loads(ALIASES.read_text())["aliases"]
    rows, unmapped, notes = [], set(), []

    for path in sorted(CAPTURES.glob("*.json")):
        cap = json.loads(path.read_text())
        standings = cap["standings"]

        # The captures are ordered tables, so position is row order. The site's
        # own numbering is checked against it rather than trusted: RSSSF has a
        # season where the printed numbers skip one and repeat another, and
        # there is no reason to assume the IFA never does.
        printed = [s["position"] for s in standings]
        if printed != list(range(1, len(standings) + 1)):
            print(f"  {path.name}: printed positions are not a contiguous 1..N "
                  f"({printed}); using row order")

        for i, entry in enumerate(standings, start=1):
            name = entry["club"]
            club = aliases.get(name)
            if club is None:
                unmapped.add(name)
                continue
            rows.append({
                "season": cap["season"],
                "season_start": cap["season_start"],
                "league": cap["league"],
                "division": cap["division"],
                "position": i,
                "club": club,
            })

        if cap.get("note"):
            notes.append(f"  {path.name}: {cap['note']}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["season", "season_start", "league",
                                           "division", "position", "club"])
        w.writeheader()
        w.writerows(rows)

    seasons = {(r["season"], r["league"], r["division"]) for r in rows}
    print(f"{len(rows)} rows from {len(seasons)} league-seasons -> {OUT}")
    if notes:
        print("notes on the captures:")
        print("\n".join(notes))
    if unmapped:
        # Unlike the Wikipedia parsers this is a hard stop. A capture is a whole
        # final table; dropping a club from it would renumber everyone below
        # them, turning a missing alias into wrong positions rather than a
        # missing row.
        raise SystemExit(
            f"{len(unmapped)} club names missing from data/aliases_ifa.json:\n  "
            + "\n  ".join(sorted(unmapped)))


if __name__ == "__main__":
    main()
